#pragma once

#define TIMEPLUS_CPP_VERSION_MAJOR 2
#define TIMEPLUS_CPP_VERSION_MINOR 5
#define TIMEPLUS_CPP_VERSION_PATCH 1

#define TIMEPLUS_CPP_VERSION_BUILD 0

// Expecting each version component to be less than 99
#define TIMEPLUS_CPP_VERSION \
    TIMEPLUS_CPP_VERSION_MAJOR *   100 * 100 * 100 \
    + TIMEPLUS_CPP_VERSION_MINOR * 100 * 100 \
    + TIMEPLUS_CPP_VERSION_PATCH * 100 \
    + TIMEPLUS_CPP_VERSION_BUILD
